### PR TITLE
Move to GTK+ version 3

### LINKED ISSUE #106: AttributeError: When using gi.repository you must not import static modules like "gobject".
When using pyperclip in Ubuntu Artful, we are hitting the following AttributeError from pygobject:

AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183

For a much more detailed explanation and debug please see:
https://bugs.launchpad.net/ubuntu/+source/python-pyperclip/+bug/1722553

To reproduced this on Ubuntu Artful all you need to do is:

#!/usr/bin/env python
import keyring  # imports gi
import pyperclip  # imports gtk
pyperclip.paste()

Narrowing down a bit more, this can also be reproduced with the following python script:

#!/usr/bin/env python
import gtk
import gi

The 2 lines of code that appear to be conflicting are:
1) /usr/lib/python2.7/dist-packages/keyrings/alt/Gnome.py
   import gi
2) /usr/lib/python2.7/dist-packages/pyperclip/clipboards.py
   import gtk

And if I understand correctly from https://bugzilla.gnome.org/show_bug.cgi?id=709183, this is importing gtk+2 modules via 'import gtk' as well as gtk+3 modules via 'import gi' which causes module conflicts (according to the same bug).

From http://www.pygtk.org/: Note: New users are encouraged to use GTK+3 through the PyGObject bindings instead of using PyGTK with GTK+2.

So it seems to me that pyperclip in artful needs to move to GTK+3. Artful is set to release this week, but we can still backport a patch from upstream post release as a stable release update.

### PR DESCRIPTION
**Pull request by coreycb**
Fixes #106

### CODE REVIEW

**Comment by asweigart** [comment]
This change seems to break Python 2's use of pyperclip. For Python 2 I would run `apt-get install python-gtk2-dev` to get the gtk module, but this change seems like it would break that. I can run `import gi` just fine from Python 3 on Ubuntu, but `import gi` doesn't work for Python 2.

What's the solution that doesn't break backwards compatibility? Is backwards compatibility important here?

**Comment by tleonhardt** [comment]
I would say that ``pyperclip`` working both with Python 2 and Python 3 is still essential at this point.  Maybe in another year Python 2 support for new releases won't matter.  But I know at this point I still have a lot of ``cmd2`` end users who are still using Python 2.  (I think they are nuts, but that is beside the point)

**Comment by coreycb** [comment]
Are you able to apt install python-gi? python3-gi should also be available for py3.

**Comment by tleonhardt** [comment]
The **python-gi** package exists in apt repos for Ubuntu 17.10, Ubuntu 16.04, Debian 9, and Debian 8 (all of the Linux VMs I had on hand to verify).

@coreycb 
Just curious, is there an equivalent package which can be installed via ``pip``?

**Comment by coreycb** [comment]
@tleonhardt I just checked and python-pi is available back to 12.04 for and looks to be available back to Debian 7. I'm not sure if there is a pip installable package. I didn't see one in my searches.

**Comment by asweigart** [comment]
I was just wondering if there was a way to still support people who have the older gtk module and not gi. Maybe we should add a `init_gi_clipboard()` instead of replacing the current `init_gtk_clipboard()`. If there's an incompatibility issue, how about we attempt to import gi first, and if that fails, then try to import gtk?

I'm not familiar with gtk on Linux. Does this make sense? Or do we have to necessarily get rid of the `import gtk` stuff?

**Comment by coreycb** [comment]
I'm ok with a fallback mode. If we did that I'd prefer importing gi first and falling back to gtk, because the import of gtk is why cmd2 and pyperclip currently fail when using interactive mode in Ubuntu. The gtk2 and gtk3 modules conflict.

**Comment by coreycb** [comment]
Note: You may also need libgtk-3-dev installed.

**Comment by coreycb** [comment]
@asweigart I've made some updates to fall back to gtk if gi is not available.

**Comment by coreycb** [comment]
@asweigart does this patch look ok to you? I really want to get this into ubuntu but would like it to land upstream here first.

**Comment by tleonhardt** [comment]
@asweigart Al, if you are busy, I'd be willing to help maintain ``pyperclip``.

**Comment by sdelafond** [comment]
Any news on this one ? An up-to-date patch is at https://github.com/sdelafond/pyperclip/blob/debian/master/debian/patches/move-to-gtk3.patch, just in case .

**Comment by asweigart** [comment]
Closing this. Thanks for your contributions and I'm sorry this slipped past my attention. I finally have some time to sort through the issues and PRs for pyperclip. I'll be adding you to the authors document so you can get recognition for your contribution.

**Pull request closed without merging**
