### PR TITLE
refactor/simplify python2/3 compatibility

### PR DESCRIPTION
**Pull request by Digenis**
This gets rid of the try/except blocks.

### CODE REVIEW

**Comment by Digenis** [comment]
tested with xclip/xsel and both pythons

**Comment by Digenis** [comment]
Did you test on other platforms?
I didn't have the chance to.

**Comment by asweigart** [comment]
I tested on Windows and it works fine. I can test on Mac in a couple hours.

**Comment by asweigart** [comment]
Tested on Python 2.6 and 3.4 on Mac OS X, it works.

**Pull request merged**
