### PR TITLE
Remove deprecated libraries (pyqt4, pygtk)

### PR DESCRIPTION
**Pull request by stephenfin**
Both the PyGTK and PyQt4 libraries have been unsupported for many years. They
complicate the codebase and it's time we drop support for them. If people still
care about these, they can use older versions of pyperclip.

### CODE REVIEW

**Comment by jakemraz** [comment]
awesome. it's hard to install pyqt4 on the recent ubuntu. please applying this PR to the latest!

**Comment by snowman2** [comment]
Seeing similar issues with gtk. Looks like others are trying to avoid them with their implementations in #233 & #182. Are there blockers preventing this PR (or one of the others) from being merged?

**Comment by snowman2** [comment]
Related #111

**Comment by asweigart** [comment]
Thanks!

**Pull request merged**
