### PR TITLE
Add support for KDE klipper.

### PR DESCRIPTION
**Pull request by contrixed**
This commit adds the support to communicate with KDE klipper via DBUS.

### CODE REVIEW

**Comment by contrixed** [comment]
Currently i am re-writing the current method to use subprocess rather than relying on DBUS. I will push it shortly.

**Comment by contrixed** [comment]
The current method now functions with Python 2 and Python 3 and has been fully tested.

**Comment by asweigart** [comment]
Thanks a lot! I'll load a linux install with KDE to test these as soon as I can.

**Comment by contrixed** [comment]
No problem! let me know your results with both versions of Python.

**Comment by drakulavich** [comment]
Hello @contrixed!

I have tested your changes in VM with Klipper 0.9.7 and KDE 4.14.11. Both Python versions works (3.4.3 and 2.7.10). Great work!

But I suggest to remove strip method in _pasteKlipper function, because it breaks consistency with other paste functions.

**Comment by contrixed** [comment]
@drakulavich  @asweigart  There could have been a reason for me doing so, not sure at this point been a little while, if any bugs come from the removal just add it back.  Thank you for the merge!

**Comment by asweigart** [comment]
Merged this in. Sorry for the delay. Thanks!

**Pull request merged**
