### PR TITLE
Mac OS name is 'posix'

### LINKED ISSUE #76: Pyperclip not working on MacOS Sierra?
Hello, I'm going through Automate the boring stuff with Python and I couldn't make pyperclip work for me.

If I run `pyperclip.copy('Hello World')` and then `pyperclip.paste()` all I get is `u''`. I know the 'u' is for unicode, but why isn't it working with my clipboard?

I'm sorry if the question is a bit vague. I'm still pretty noob.

### PR DESCRIPTION
**Pull request by hugovk**
Closes #76.

```
Python 2.7.12 (default, Sep 28 2016, 18:41:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
.>>> import os
>>> os.name
'posix'
>>> import platform
>>> platform.system()
'Darwin'
>>> 
```

### CODE REVIEW

**Comment by asweigart** [comment]
Sorry for the delay in responding to this.

I'm not sure how this solves the problem. Even is OS X no longer has an os.name of 'mac', the platform.system() call will still return 'Darwin' and the OS X clipboard functions should be returned. Further, Linux also has an os.name of 'posix', so this would cause Linux systems to attempt to use the OS X clipboard functions.

Are we sure the problem in issue #76 is due to this line of code?

**Comment by hugovk** [comment]
On further testing, you're correct, this doesn't fix it. 

`init_osx_clipboard()` is called regardless, but the problem still occurs in IDLE (it's fine via a script).

With some debugging lines added:
```
± python
Python 3.6.3 (default, Oct  4 2017, 06:09:15)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyperclip
posix
Darwin
init
>>> pyperclip.copy('Hello World')
>>> pyperclip.paste()
'pyperclip.paste()'
>>>
```

More investigation is needed.

**Comment by hugovk** [comment]
Installing latest master https://github.com/asweigart/pyperclip/commit/d4faa6bd36b9e29ba57b7bee5e31ba3c1dab0cdf (`pip install -U git+https://github.com/asweigart/pyperclip`) has another problem (Python 2.7.14 and 3.6.3, IDLE and via script):

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    pyperclip.copy('Hello World')
  File "/usr/local/lib/python3.6/site-packages/pyperclip/clipboards.py", line 24, in copy_osx_cmd
    p.communicate(input=text.encode(ENCODING))
LookupError: unknown encoding: uft-8
``

**Comment by asweigart** [comment]
Oof, that was a careless mistake on my part. It's fixed now and you should be able to update it from pypi.

**Pull request merged**
