### PR TITLE
Replace `wcscpy_s` with `memmove` for Windows.

### LINKED ISSUE #51: Pyperclip does not work on Windows XP 32-bit
Pyperclip doesn't work on WIndows XP 32-bit (and possibly 64-bit too). When installing, the following output is received:

    C:\Python34\Scripts>pip install pyperclip
    Collecting pyperclip
      Using cached pyperclip-1.5.24.zip
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "C:\DOCUME~1\admin\LOCALS~1\Temp\pip-build-ncweabkc\pyperclip\setup.p
    y", line 8, in <module>
            version=__import__('pyperclip').__version__,
          File "C:\DOCUME~1\admin\LOCALS~1\Temp\pip-build-ncweabkc\pyperclip\pypercl
    ip\__init__.py", line 103, in <module>
            copy, paste = determine_clipboard()
          File "C:\DOCUME~1\admin\LOCALS~1\Temp\pip-build-ncweabkc\pyperclip\pypercl
    ip\__init__.py", line 53, in determine_clipboard
            return init_windows_clipboard()
          File "C:\DOCUME~1\admin\LOCALS~1\Temp\pip-build-ncweabkc\pyperclip\pypercl
    ip\windows.py", line 75, in init_windows_clipboard
            wcscpy_s = ctypes.cdll.msvcrt.wcscpy_s
          File "C:\Python34\lib\ctypes\__init__.py", line 364, in __getattr__
            func = self.__getitem__(name)
          File "C:\Python34\lib\ctypes\__init__.py", line 369, in __getitem__
            func = self._FuncPtr((name_or_ordinal, self))
        AttributeError: function 'wcscpy_s' not found

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\DOCUME~1\admin
    \LOCALS~1\Temp\pip-build-ncweabkc\pyperclip

When I try to modify the code to use `ctypes.cdll.msvcrt.wcscpy` instead of `ctypes.cdll.msvcrt.wcscpy_s`, this quick fix just results in this error:

    >>> import pyperclip
    >>> pyperclip.copy('howdy')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Python34\pyperclip\windows.py", line 142, in copy_windows
        if wcscpy_s(c_wchar_p(locked_handle), count, c_wchar_p(text)):
    OSError: exception: access violation reading 0x00000006

This is probably an issue that wcscpy_s doesn't exist in the old msvcrt.dll. I was able to replicate this in a VM. I'm not sure if this can be fixed by updating the dll, but we should come up with a better solution than that.

### PR DESCRIPTION
**Pull request by tmr232**
Closes #51.

### CODE REVIEW

**Comment by mhils** [comment]
LGTM :+1:

**Comment by asweigart** [comment]
Sorry again for the delay on this. If you want to ping me, you can also email me at asweigart@gmail.com

**Comment by asweigart** [comment]
Thanks for the PR and review!

**Comment by tmr232** [comment]
@asweigart How long before this gets updated in PyPI as well?

**Comment by asweigart** [comment]
Just pushed it. Thanks!

**Pull request merged**
