### PR TITLE
Optimize exception.

### PR DESCRIPTION
**Pull request by contrixed**
Using format will optimize the exception in terms of speed.

### CODE REVIEW

**Comment by asweigart** [comment]
Sorry. The '{}' syntax isn't supported by Python 2.6. It raises a "ValueError: zero length field name in format" error.

**Comment by drakulavich** [comment]
'{0}'.format(foo) is correct syntax for Python 2.6. As far as I know, '{}' syntax works only in Python 3.
Also [.format is slower](http://tomatohater.com/2013/08/30/python-performance-string-formatting/) than percent formatting.

**Comment by contrixed** [comment]
Incorrect @drakulavich here's proof with Python 2.7
```python
20:49 $ python
Python 2.7.9 (default, Dec 29 2014, 06:44:46) 
[GCC 4.8.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> '{}'.format('a')
'a'
```

**Comment by asweigart** [comment]
Ah yes, but this syntax doesn't work with 2.6:

Python 2.6.6 (r266:84297, Aug 24 2010, 18:46:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> '{}'.format('hello')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: zero length field name in format
>>>

**Comment by Tatsh** [comment]
In Python 2.6, numbers must be given for `.format()` to work.

```python
'{0}'.format('a')
```

https://docs.python.org/2.6/library/stdtypes.html#str.format

**Pull request closed without merging**
