### PR TITLE
Improve Testability

### LINKED ISSUE #36: "Cannot connect to X server"
We have multiple mitmproxy users who are apparently facing an issue caused by pyperclip trying to initialize some GUI framework (?) and then `sys.exit()`ing (?): https://github.com/mitmproxy/mitmproxy/issues/701#issuecomment-152245629

Any ideas/pointers what could cause this? A fix for this would be highly appreciated. :smiley:

### PR DESCRIPTION
**Pull request by mhils**
This PR tries to fix the overall test situation of pyperclip - that is, it automatically runs the tests for all available clipboard mechanisms. I considered adding travis and appveyor integration, but that's probably not too useful given that they don't run X servers. To make this work nicely I had to shift some bytes around - sorry for that.

This PR also fixes #36 by requiring `$DISPLAY` to be set and adds GitHub's standard .gitignore for Python projects.

@asweigart: I'd personally love to see a fix for #36 shipped ASAP as it breaks mitmproxy completely on machines without X server - if you're super busy at the moment please give us a quick ping so that we can fork.

Thanks!
Max

### CODE REVIEW

**Comment by asweigart** [comment]
This looks good. I'd like to merge it pronto, but I can't get the test to run. It says it cannot find the pyperclip module when I try to import it. Previously, I had "sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))" to handle this, but is this not the best Python practice?

What steps would I need to do to run test_copy_paste.py?

**Comment by mhils** [comment]
Gald you find it useful. You can run `pip install -e .` in the root directory, which installs pyperclip as  an editable development package: http://pip.readthedocs.org/en/stable/reference/pip_install/#editable-installs

**Comment by asweigart** [comment]
Running ``pip install -e .`` installs it and it works. But when I run the test script again, it gets past the ``import pyperclip`` line, but then has this error:

    Traceback (most recent call last):
      File "tests\test_copy_paste.py", line 7, in <module>
        from pyperclip import _executable_exists
    ImportError: cannot import name _executable_exists

This seems to happen no matter which directory I run the test script from. Is there some other step I need to do? (I'll consult the pip and import statement docs in the meantime.)

**Comment by mhils** [comment]
This looks like there's a second ("old") pyperclip installation present. If you `pip uninstall pyperclip`, does `python -c 'import pyperclip'` still work?

**Comment by asweigart** [comment]
I'm still getting that error on Windows 7 for both Python 2.7 and 3.4. It seems to work on Ubuntu running in VirtualBox, so it's probably just a weird Windows issue. I'll merge this and open a new issue about the Windows thing.

**Comment by mhils** [comment]
Thanks! FWIW, I'm running this just fine on Windows and Ubuntu. Feel free to drop by our [mitmproxy Slack channel](http://slack.mitmproxy.org) if you want me to take a look! :smiley:

**Pull request merged**
